void AddAdventurerGauntletScripts();
void AddAdventurerGauntletPermadeathScripts();
void AddAdventurerGauntletScalingScripts();
void AddAdventurerGauntletAccountStashScripts();
void AddAdventurerGauntletAccountCollectionScripts();
void AddAdventurerGauntletLoneWolfScripts();
void AddAdventurerGauntletCelebrationScripts();
void AddAdventurerGauntletCuratedRewardsScripts();
void AddAdventurerGauntletSetsScripts();
