void AddAdventurerGauntletScripts();
void AddAdventurerGauntletPermadeathScripts();
void AddAdventurerGauntletScalingScripts();
void AddAdventurerGauntletRunReconnectScripts();
void AddAdventurerGauntletAccountStashScripts();
void AddAdventurerGauntletAccountCollectionScripts();
void AddAdventurerGauntletCelebrationScripts();
void AddAdventurerGauntletCuratedRewardsScripts();
void AddAdventurerGauntletSetsScripts();
