-- Adventurer Gauntlet: dedicated expedition reward chest.
-- Clone a stock Battered Chest (106318) so the client needs no custom model.
-- The chest is intentionally empty for this milestone; gauntlet loot is generated by code later.

SET @GAUNTLET_CHEST_SOURCE := 106318;
SET @GAUNTLET_CHEST_ENTRY := 910001;

DELETE FROM `gameobject_template` WHERE `entry` = @GAUNTLET_CHEST_ENTRY;
DROP TEMPORARY TABLE IF EXISTS `tmp_adventurer_gauntlet_chest`;
CREATE TEMPORARY TABLE `tmp_adventurer_gauntlet_chest` AS
    SELECT * FROM `gameobject_template` WHERE `entry` = @GAUNTLET_CHEST_SOURCE;
UPDATE `tmp_adventurer_gauntlet_chest`
SET
    `entry` = @GAUNTLET_CHEST_ENTRY,
    `name` = 'Cofre de Expedicion',
    `Data0` = 0,
    `Data1` = 0,
    `AIName` = '',
    `ScriptName` = '';
INSERT INTO `gameobject_template` SELECT * FROM `tmp_adventurer_gauntlet_chest`;
DROP TEMPORARY TABLE `tmp_adventurer_gauntlet_chest`;
